// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etlafnrnqyitdhatazut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0bGFmbnJucXlpdGRoYXRhenV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDUwODcsImV4cCI6MjA2NDcyMTA4N30.NjiLGtfheJ9IugEKZ3S-x4jEIeABLyCnGn1AyIKXhRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);